### ISSUE TITLE
Docker image fails node-kafkard install - nodeJS sample

### ISSUE THREAD

**Issue by Nafling** [ibm-messaging/message-hub-samples#27]
Hi guys. I get an error when I install run docker build with the current Dockerfile in the nodeJS sample.

The error:

/usr/src/app/node_modules/bindings/bindings.js:88
        throw e
        ^

Error: /usr/src/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node: invalid ELF header
    at Error (native)
    at Object.Module._extensions..node (module.js:604:18)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at bindings (/usr/src/app/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/usr/src/app/node_modules/node-rdkafka/librdkafka.js:10:32)
    at Module._compile (module.js:577:32)

My current fixes are the following two steps:

1) Boron without "extensions" seem to be installing an older version of node - so I use node:8.9.0-slim, it also works well with alpine, thanks to "webmastersteave"

2)There seem to be a problem with installing node-kafkard from the package file, so I have had success in putting the npm command directly in the dockerfile.

Does this make sense?

**Comment by mimaison** [comment]
This issue happened because the dockerfile would include your local `node-modules` folder inside the image. Hence when running it, it would try to run the binaries built on your local machine inside the Linux container and fail.

We've fixed the dockerfile so it should work now. Closing
