### ISSUE TITLE
Error: Invalid value for configuration property "security.protocol" for local installation

### ISSUE THREAD

**Issue by bttong** [ibm-messaging/message-hub-samples#31]
Hi,
I'm trying the sample locally on OS X and got this issue:
Error: Invalid value for configuration property "security.protocol"
    at KafkaConsumer.Client (/Users/btong/MyWork/github/message-hub-samples/kafka-nodejs-console-sample/node_modules/node-rdkafka/lib/client.js:54:18)
    at new KafkaConsumer (/Users/btong/MyWork/github/message-hub-samples/kafka-nodejs-console-sample/node_modules/node-rdkafka/lib/kafka-consumer.js:118:10)
    at Object.exports.buildConsumer (/Users/btong/MyWork/github/message-hub-samples/kafka-nodejs-console-sample/consumerLoop.js:38:16)
    at runLoops (/Users/btong/MyWork/github/message-hub-samples/kafka-nodejs-console-sample/app.js:205:33)
    at /Users/btong/MyWork/github/message-hub-samples/kafka-nodejs-console-sample/app.js:165:9
    at _fulfilled (/Users/btong/MyWork/github/message-hub-samples/kafka-nodejs-console-sample/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/Users/btong/MyWork/github/message-hub-samples/kafka-nodejs-console-sample/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/Users/btong/MyWork/github/message-hub-samples/kafka-nodejs-console-sample/node_modules/q/q.js:816:13)
    at /Users/btong/MyWork/github/message-hub-samples/kafka-nodejs-console-sample/node_modules/q/q.js:624:44
    at runSingle (/Users/btong/MyWork/github/message-hub-samples/kafka-nodejs-console-sample/node_modules/q/q.js:137:13)

I'm not sure if I generate the .pem key correctly.  Could you please point me to instructions on how to do so?

**Comment by alex-thewsey-ibm** [comment]
Hi @bttong I had problems like this for a while when starting out with the package

npm install / yarn add `node-rdkafka` will often succeed even if your system doesn't have the dependencies required for SSL: `node-gyp` will build `librdkafka` from source _without SSL (or SASL) support_ and still report the installation as a success: Resulting in "invalid configuration property" at run time.

I recommend you delete your `node_modules` folder, check again you satisfy all the [MacOS deployment criteria](https://github.com/ibm-messaging/message-hub-samples/blob/master/kafka-nodejs-console-sample/local.md) and re-run npm install (or yarn).

Maybe useful to note openssl does have to be installed _via brew_: it didn't work for me first time with it installed another way.

If you're still struggling, could you post your NPM/yarn install log to check what dependencies might be missing? Especially the sections where librdkafka build configuration is printed out

**Comment by bttong** [comment]
Thanks.  Clearing out the node_modules helped.
